// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krpykzpjnizjkcgdjpjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycHlrenBqbml6amtjZ2RqcGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzA1OTAsImV4cCI6MjA2Mzg0NjU5MH0.HxeWTUBz5W99v23YMxnGn_aWqh6rKj_QL-v2WjaQQIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);